import numpy as np
import matplotlib.pyplot as plt
import tifffile
import gc
# import sys
# import os
# from tkinter import *
# from tkinter import filedialog
# from cellpose import denoise#, utils, io
import cv2
import matplotlib
matplotlib.use("Qt5Agg")


"""
2025/03/13, written right after receiving phone call at 08:27 from Morosawa.

This code is made specifically based on Morosawa's request, to generate graph of comparing OCT vs NC200 in 
'viability' assay. 
* 
NOTE: the data (Jurkat cell, 2024/07/31) was measured with unstable galvo, therefore any quantification is 
100% irresponsible and unreliable; the raw data was even lost in an HDD blackout accident.

*** NO QUANTIFICATION IS RELIABLE ! ! ! ***
I hereby declare: the result has ZERO scientific value for sharing and discussing, NO ONE SHOULD MAKE ANY 
CONCLUSION from it. 
Any action of using this graph to persuade investors / collaborators / customers / researchers is recognized 
as severely TREATING, and anyone doing so should NEVER BE TRUSTED in BUSINESS REPUTATION and SCIENTIFIC MORALITY.
* 
All code below is generated by ChatGPT directly following the request Morosawa, I hold no responsibility 
of fabricating, spreading, and treating using any FAKE DATA. 
"""



dead_threshold = 0.4
live_threshold = 0.2

def count_red_green_pixels(image_path, hue_threshold):
    img = cv2.imread(image_path)
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    hue, sat, val = hsv[:, :, 0], hsv[:, :, 1], hsv[:, :, 2]
    red_mask = (hue < hue_threshold*150) & (val > 10)
    green_mask = (hue > hue_threshold*150) & (val > 10)
    red_count = np.sum(red_mask)
    green_count = np.sum(green_mask)
    green_percentage = green_count / (red_count + green_count)
    # print(f"Red pixels: {red_count}")
    # print(f"Green pixels: {green_count}")
    # print(f"Green pixel percentage is: {green_percentage}")
    return green_percentage


control_0 = r"C:\Users\lzhu\Desktop\PhotonicsWest2024\control0.png"
control_19 = r"C:\Users\lzhu\Desktop\PhotonicsWest2024\control19.png"
oxydol_0 = r"C:\Users\lzhu\Desktop\PhotonicsWest2024\oxydol0.png"
oxydol_19 = r"C:\Users\lzhu\Desktop\PhotonicsWest2024\oxydol19.png"

via_con0 = count_red_green_pixels(control_0, live_threshold) * 100
via_con19 = count_red_green_pixels(control_19, live_threshold) * 100
via_oxy0 = count_red_green_pixels(oxydol_0, dead_threshold) * 100
via_oxy19 = count_red_green_pixels(oxydol_19, dead_threshold) * 100

print(f"Live: {"%.0f" % via_con0} >> {"%.0f" % via_con19}")
print(f"Dead: {"%.0f" % via_oxy0} >> {"%.0f" % via_oxy19}")